syntax = "proto3";
package com.staploy;
import "app.proto";

enum TaskRegistryTypes {
  REGISTRY_NONE = 0;

  TASK_PUSH = 1;
  TASK_PULL = 2;
  TASK_REMOVE = 3;
  TASK_LIST = 4;

  LOCAL_PULL_PACKAGE = 5;
  LOCAL_LIST_REPOSITORY = 6;
  LOCAL_ADD_REPOSITORY = 7;
  LOCAL_REMOVE_REPOSITORY = 8;
  LOCAL_MANAGE_TOKEN_REPOSITORY = 9;
  LOCAL_PACKAGE_QUERY = 10;
  LOCAL_PACKAGE_CACHE_UPDATE = 11;
}

message RegistryRequestPacket {
  TaskRegistryTypes taskType = 1;
  optional AppInfoFetch appInfo = 2;
  optional string blobId = 3;
  optional string repositoryUrl = 4;
}

message RegistryResponsePacket {
  repeated InstalledAppInfo appInfo = 1;
  optional string blobId = 2;
  repeated string repositoryUrl = 3;
}
